CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    is_active BOOLEAN NOT NULL DEFAULT true
);
CREATE TABLE IF NOT EXISTS inquiries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(100) NOT NULL,
    body TEXT NOT NULL,
    requester_name VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    assignee_id BIGINT REFERENCES users(id),
    priority VARCHAR(10) NOT NULL DEFAULT 'MIDDLE',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at DATETIME DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS inquiry_histories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    inquiry_id BIGINT NOT NULL,
    changed_by BIGINT NOT NULL,
    field_name VARCHAR(20) NOT NULL,
    old_value VARCHAR(50) DEFAULT NULL,
    new_value VARCHAR(50) DEFAULT NULL,
    changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
